### ISSUE TITLE
Your webpage is not responding ;) and I got 0 channels [questions]

### ISSUE THREAD

**Issue by Behinder** [jeffdoubleyou/hdhomerun-live#5]
I wanted contact you but cannot find email and your website is down so I write here.
Tuner is detected but I get 0 channels. There is no way to scan channels because there is nothing on localhost/lineup.html. I already have web server on 80 port and thought that was interfering so I changed http port in your config to 8000 - result is the same.

I am trying to create my own HDHomeRun emulation for using with iptv streams. Unfortunately SiliconDust documentation is very vague about their API so If you don't mind few questions, maybe it could help other people as well.

1. Do we really need two web servers - one for http and another for media? 
2. I creted express web server with nodejs with two endpoints exposed - /lineup.json and /discover.json -is it something more needed?
3. Particularly ad.2) what is necessary to make tuner 'discoverable' on network? should I create websocket? how, on which port, is tuner broadcasting on UDP or TCP?

Also, it could be usefull if we could have support for MusicChoice. Their radio channels unfortunately are HLS video so to play only audio reencoding and send to e.g. icecast server would be required but then we can lost information about who is playing at the moment. It's also very difficult to extract their live streams link from the site. However MusicChoice is supported by TV Everywhere platform so I assume same principle with Puppeteer could aply.

Thanks in advance.

**Comment by jeffdoubleyou** [comment]
HI Behinder,

You do need two web servers one multicast server for the device discovery and the control server to send communicate with the server from your client.

discover.json should simply return information about the tuner.  The lineup.json returns a list of channels and the URL to play them, and it's only populated after scanning channels.

I haven't used this in forever and it's likely that it no longer works with the TV everywhere channel scraping.  I abandoned this project because the TV software that I use now natively supports TVE so I have no need.

If you don't need to scrape TV Everywhere sites for playlists, you should be able to simply populate the channel list in the settings manually or implement some other method of scanning that would be much easier than the puppeteer URL scraping anyway.

You can see how each request is handled in the lib/HTTPRequestHandler.js file.

And all of the endpoints are listed in multicast.js:

`let tuners = [];
for(let i=0; i<deviceConfig.TunerCount; i++) {
    tuners.push(`/tuner${i}/:channelNum`);
}
http.use(express.static('static'));
http.use(morgan('dev'));
http.get('/lineup.json', httpRequest.Lineup);
http.get('/lineup_status.json', httpRequest.LineupStatus);
http.post('/lineup_status.json', httpRequest.LineupStatus);
http.post('/lineup.post', httpRequest.Scan);
http.get('/discover.json', httpRequest.Discover);
http.get('/stream/:channelNum', httpRequest.Play);
http.get('/auto/:channelNum', httpRequest.Play);
http.get(tuners, httpRequest.Play);`

**Comment by Behinder** [comment]
Thanks for informative answer, I couldn't invent such code myself
especially this in protocol.js  and creating sockets (I thought right that
UDP is needed)
I'll try to analyse your code further but at least one thing evade my
intellect.
I dont understand relation between /stream/:chanelNum and streamURL.

If you get stream URL from the provider side how the server know that
on/stream/:channelNum (or like in my old HDHomeRun /auto/v:number) is
associated with particular URL? :)
